#!/bin/bash

# Simple script to create a journal entry for a given day, in an appropriately structured folder system

# Change directory to the journal directory
# Update this if using on your local system.
cd ~/repos/diatribes

echo "Creating Journal file for today, $(date)"

NOW=$(date "+%A %Y %m %d %B")

YEAR=$(echo $NOW | awk '{ print $2 }')
MONTH_FOLDER=$(echo $NOW | awk '{ print $3 }')-$(echo $NOW | awk '{ print $5 }')
MONTH_NAME=$(echo $NOW | awk '{ print $5 }')
DAY=$(echo $NOW | awk '{ print $4 }')
DAY_NAME=$(echo $NOW | awk '{ print $1 }')
FILE_NAME=$DAY-$DAY_NAME.md

# Create the year/month folders and file, if necessary

if [ -d $YEAR ]
then
    echo $YEAR directory already exists
else
    mkdir $YEAR
fi

cd ./$YEAR

if [ -d $MONTH_FOLDER ]
then
    echo $MONTH_FOLDER directory already exists
else
    mkdir $MONTH_FOLDER
fi

cd ./$MONTH_FOLDER

if [ -a $FILE_NAME ]
then
    echo $FILE_NAME file already exists
else
    touch $FILE_NAME
    echo -e "# $DAY_NAME, $MONTH_NAME $DAY $YEAR\n" > $FILE_NAME
fi

# Open the file in VS Code

code $FILE_NAME
